spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/test #SHOULD BE DEFINED
    username: test #SHOULD BE DEFINED
    password: test #SHOULD BE DEFINED
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 8
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      max-lifetime: 600000
      connection-timeout: 30000
      initialization-fail-timeout: 10000
      driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: validate
        default_schema: discovery
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true
#    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
